---
- name: Playbook to configure ansible controller post installation
  hosts: localhost
  connection: local
  vars:
    controller_validate_certs: false
    controller_hostname: https://ec2-35-180-45-139.eu-west-3.compute.amazonaws.com
    controller_oauthtoken: 8foQfAGbuyaY5DaFkocMjs3lloEoJ8
  collections:
    - ansible.controller
